workflows:
  build-and-release:
    name: Build and Release
    environment:
      flutter: latest
    script:
       - flutter pub get
       - flutter build apk
    artifacts:
      - build/app/outputs/apk/release/**/*.apk
    publishing:
      email:
        recipients:
          - mnsdiam@hotmail.gr
    #  google_play:
     #   service_account_file: google-play.json
      #  track: internal
       # apk: build/app/outputs/apk/release/app-release.apk
