name: Flutter Build
env: flutter
flutterVersion: stable

workflows:
    android-workflow-id:
        name: Flutter Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1

script:
# Build for Android
  - flutter pub get
  - flutter build apk
artifacts:
  - build/app/outputs/**/*.apk
  - build/app/outputs/apk/release/app-release.apk

envVars:
  - FLUTTER_STAGE: stable
  
scripts:
      - flutter pub get
      - flutter build apk --release
      
notifications:
  email:
    recipients:
    - mnsdiam@hotmail.gr
    - mochosgate1@gmail.com
