# Codemagic YAML configuration file
# https://docs.codemagic.io/getting-started/configuration

workflows:
  build-and-release:
    name: Build and release Android app
    environment:
      vars:
        ANDROID_SDK_ROOT: /usr/local/android-sdk
    script:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/apk/release/**/*.apk
    publishing:
      email:
        recipients:
          - mnsdiam@hotmail.gr
      release_notes: "This is a release."
      track: production
      mapping:
        app: build/app/outputs/apk/release/app.apk
