# The name of the build configuration. This can be any string.
name: Flutter Build
env: flutter
flutterVersion: stable
workflows:
  build-and-release:
   # name: Build and Release
    environment:
      flutter: stable
      script:
    - name: Set up local.properties
      script: | 
        echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
    - name: Get Flutter packages
      script: | 
        flutter packages pub get
    - name: Build AAB with Flutter
      script: | 
        flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    #scripts:
     #  - flutter pub get
      # - flutter build apk
    #artifacts:
     # - build/app/outputs/apk/release/**/*.apk
   # publishing:
    #  email:
    #    recipients:
    #      - mnsdiam@hotmail.gr
    #  google_play:
     #   service_account_file: google-play.json
      #  track: internal
       # apk: build/app/outputs/apk/release/app-release.apk
workflows:
  sample-workflow-id:
    environment: 
      # ...
    scripts: 
      # ...
    publishing: 
      email:
        recipients:
          - mnsdiam@hotmail.gr
          - mochosgate1@gmail.com
        notify:
          success: true
          failure: false

  
