name: Flutter Build
env: flutter
flutterVersion: stable
envVars:
  - FLUTTER_STAGE: stable    

workflows:
    android-workflow-id:
        name: Flutter Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1

script:
# Build for Android
  - flutter pub get
  - flutter build apk
  - flutter build apk --release

artifacts:
  - build/app/outputs/**/*.apk
  - build/app/outputs/apk/release/app-release.apk

notifications:
  email:
    recipients:
    - mnsdiam@hotmail.gr
    - mochosgate1@gmail.com
